[theme]
name = "plain"

[theme.overrides]
separator = "|"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a❘%d.%m❘%H:%M"
