library: ~/archive/music/music.db
directory: ~/archive/music
plugins: chroma fromfilename fetchart mbsync scrub info missing
asciify_paths: yes
art_filename: albumart
threaded: yes
original_date: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>"\?\*\|]': _
    '\s+$': ''
    '^\s+': ''

import:
    #log: import.log
    languages: en

paths:
    default: $albumartist/$year - $album/$track $title
    comp: _compilations/$year - $album/$track $title
    singleton: _singles/$artist - $title
